---
stages:
  - build
  - test

caches:
  - gradle

chat-backend-build:
  image: gradle:jre11
  stage: build
  only:
    changes:
      - "chat-backend/**/*"
  script:
    - cd chat-backend
    - gradle build

#chat-ui-build:
#  image: node
#  stage: build
#  onl
#    changes:
#      - "chat-ui/**/*"
#  script:
#    -
#
#chat-history-consumer-build:
#  stage: build
#  only:
#    changes:
#      - "chat-history-consumer/**/*"