#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
version: "3.8"

# "virtual" volumes for containers
volumes:
  kafka_data:
  postgres_data:
  # Currently not working in windows
  mongo_data:

services:
  # Just the zookeeper for Kafka
  kafka_zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka pipe for storing message history
  kafka:
    image: confluentinc/cp-kafka:5.5.0
    ports:
      - '19092:19092' # Forward port to outside cluster
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: kafka_zookeeper:2181
      KAFKA_CREATE_TOPICS: "messages:1:1,test:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #volumes:
    #  - ./kafka_data:/var/lib/kafka/data
    depends_on:
      - kafka_zookeeper
        

  # This "container" is a workaround to pre-create topics
  kafka-setup:
    image: confluentinc/cp-kafka:5.5.0
    depends_on:
      - kafka
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                     cub kafka-ready -b kafka:9092 1 20 && \
                     kafka-topics --create --if-not-exists --zookeeper kafka_zookeeper:2181 --partitions 1 --replication-factor 1 --topic messages && \
                     kafka-topics --create --if-not-exists --zookeeper kafka_zookeeper:2181 --partitions 1 --replication-factor 1 --topic test'"
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored

  # This is just so for development purposes only to view kafka queues with shell
  kafka-ubuntu:
    image: ubuntu:latest
    command: "bash -c 'apt-get update && \ 
              apt-get -y install iputils-ping && \
              apt-get -y install kafkacat && \
              tail -F anything'"

  # Postgres database to store the message history
  history-postgres:
    image: johannes/pg-message-history:latest
    env_file:
      - db.env.dev
    ports:
      - '15432:5432' # Forward port to outside cluster
    volumes:
      - postgres_data:/var/lib/postgresql/data